### ISSUE TITLE
yoast_seo_save_scores page was called with wrong scheme

### ISSUE THREAD

**Issue by brotkrueml** [Yoast/Yoast-SEO-for-TYPO3#256]
### Please give us a description of what happened.
I updated from version 4.1.0 to 5.0.0 and noticed some errors in the browser console:
![yoast_seo](https://user-images.githubusercontent.com/2566282/56189050-4f2f4600-6027-11e9-9252-05e3ff9eaf57.png)

The main issue I think is, that the website URL is called with https scheme, but in site configuration it is configured as http (I'm in development context):

```
rootPageId: 3
base: 'https://www.example.com/'
baseVariants:
  -
    base: 'http://example.ddev.local:8080/'
    condition: 'applicationContext == "Development"'
  -
    base: 'https://staging.example.com/'
    condition: 'applicationContext == "Production/Staging"'
  -
    base: 'http://testing.example.com/'
    condition: 'applicationContext == "Testing"'
languages:
  -
    title: English
    enabled: true
    languageId: '0'
    base: /en/
    typo3Language: default
    locale: en_US.utf8
    iso-639-1: en
    navigationTitle: English
    hreflang: en
    flag: us
  -
    title: Deutsch
    enabled: true
    languageId: '1'
    base: /de/
    typo3Language: de
    locale: de_DE.utf-8
    iso-639-1: de
    navigationTitle: Deutsch
    hreflang: de
    fallbackType: strict
    flag: de
```

### Please describe what you expected to happen and why.

To call the URL with the correct scheme.

### Technical info
* TYPO3 version: 9.5.5
* Yoast SEO version: 5.0.0
