### ISSUE TITLE
Yoast request will not work with a default language base configuration

### ISSUE THREAD

**Issue by cocolocochris** [Yoast/Yoast-SEO-for-TYPO3#302]
* [x] I've read and understood the [contribution guidelines](https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/.github/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.
We have a multilingual website.
If we use a default language base (for example "/de/") (via sites sonfig.yaml) all Yoast request will not work anymore because the URL is wrong.

### Please describe what you expected to happen and why.
It must be https://www..xyz.net/de/?type=1480321830 
It is: https://www..xyz.net/?type=1480321830 

### How can we reproduce this behavior?
1. Add in site config.yaml for the default language "base: /de/"
2. Clear caches
3. Test Yoast/Previews in backend

### Technical info
* TYPO3 version: 9.5.9
* Yoast SEO version: yoast_seo 5.1.0, yoast_seo_premium 3.0.1

**Comment by Neowar** [comment]
As an additional info:

This is because in the function "getTargetUrl" of class "YoastSeoForTypo3\\YoastSeo\\Form\\Element\\SnippetPreview" the structure of the Uri is done without passing the Language parameter.

For TYPO3 9.5 this affects this line in the current Yoast version:

Line 506:

` $uri = '/?type=' . self::FE_PREVIEW_TYPE . '&uriToCheck=' . urlencode($uriToCheck);`

Should be:

` $uri = '/?L='.$languageId.'&type=' . self::FE_PREVIEW_TYPE . '&uriToCheck=' . urlencode($uriToCheck);`

It would be even better:

`$requestUri = YoastUtility::fixAbsoluteUrl((string)$site->getRouter()->generateUri($site->getRootPageId()));`
`$uri = $requestUri . '?type=' . self::FE_PREVIEW_TYPE . '&uriToCheck=' . urlencode($uriToCheck);`

**Comment by RinyVT** [comment]
@Neowar 
Thank you for your bug report, unfortunately I am unable to reproduce your error.
Locally I have the URL https://cms9.ddev.site/
When I either set the `base` to `https://cms9.ddev.site/en/` or the language base to `/en/` for the default language, I always get result when for example this URL is requested:
`https://cms9test.ddev.site/?type=1480321830&uriToCheck=https%3A%2F%2Fcms9.ddev.site%2Fen%2Fpage`

What kind of error do you get when visiting that URL?
Unfortunately we cannot use the site router for building the URL because in a multi-domain website this will lead to CORS errors.

**Comment by Neowar** [comment]
Hi,

Sorry for the late reply. A lot of stress.

If we have the following configuration for the page, the call will fire with "https://example.net/?type=1480321830&uriToCheck=https://example.net/de/home".

Due to the following site configuration, the validation fails because a redirect (307) is thrown to "https://example.net/de/".

The same applies to the other two TypeNum defined in the yoast extension.

Our site configuration:

````
rootPageId: 1
base: 'https://example.net/'
languages:
  -
    title: German
    enabled: true
    languageId: '0'
    base: /de/
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    navigationTitle: Deutsch
    hreflang: de-DE
    direction: ltr
    flag: de
  -
    title: Englisch
    enabled: true
    languageId: '1'
    base: /en/
    typo3Language: default
    locale: en_GB.UTF-8
    iso-639-1: en
    navigationTitle: English
    hreflang: en-GB
    direction: ltr
    fallbackType: strict
    fallbacks: ''
    flag: en-us-gb
````
