### ISSUE TITLE
Unable to preview hidden pages 

### ISSUE THREAD

**Issue by stat1x** [Yoast/Yoast-SEO-for-TYPO3#309]
Using yoast_seo last v5.1.1 and TYPO3 v9.5.10, I am unable to preview hidden pages while yoast_seo is installed.
I have 2 site configurations :
main :
```
rootPageId: 1
base: '%env(DOMAIN_A)%'
baseVariants: {  }
languages:
  -
    title: Français
    enabled: true
    languageId: '0'
    base: /
    typo3Language: fr
    locale: fr_CH.UTF-8
    iso-639-1: fr
    navigationTitle: Français
    hreflang: fr-CH
    direction: ''
    fallbackType: strict
    fallbacks: ''
    flag: ch
errorHandling: {  }
routes: {  }
disableStaticFileCache: false
```
secondary :
```
rootPageId: 15
base: '%env(DOMAIN_B)%'
baseVariants: {  }
disableStaticFileCache: false
errorHandling: {  }
languages:
  -
    title: Français
    enabled: true
    languageId: '0'
    base: /
    typo3Language: fr
    locale: fr_CH.UTF-8
    iso-639-1: fr
    navigationTitle: Français
    hreflang: fr-CH
    direction: ''
    fallbackType: strict
    fallbacks: ''
    flag: ch
routes: {  }
```
If I access the backend with DOMAIN_B I cannot preview the hidden pages from DOMAIN_A. The generated link for preview is wrong. It works fine without yoast_seo.

It is due to the fact that  `getAllowedDoktypes` from YoastUtility class loads the typoscript configuration (I don't know why...). Loading the typoscript configuration before the application is running creates a wrong context (the visibility aspect is initialized with "false" as includeHiddenPages... It should be true in this case).
